// Generated by https://quicktype.io

export interface PricesResponse {
  prices: Prices;
}

export interface Prices {
  mlc: number;
  mn: number;
  usd: number;
  updatedAt?: string;
  id?: string;
}
